---
# cinder snapshot-create commands wrapper tasks

- name: cinder creating snapshot
  command: cinder snapshot-create --display-name {{ item.name }} {{ item.volume }}
  environment: "{{ keystone_env }}"
  when: cinder.snapshots is defined 